# Copyright the templig contributors.
# SPDX-License-Identifier: MPL-2.0

id:   23
name: Interesting Name
pass: {{ if hasArg "passEnv" -}}
          {{ env "PASSWORD" | required "PASSWORD required" | quote }}
      {{ else }}
          defaultPass
      {{- end }}