# SPDX-FileCopyrightText: 2026 The templig contributors.
# SPDX-License-Identifier: MPL-2.0

coverage:
    status:
        project:
            default:
                target:   95%  # the minimal overall coverage
                threshold: 1%  # allows for minimal deviation (optional)
        patch:
            default:
                target:   95%  # only newly added code must fulfill 95%