# Copyright the templig contributors.
# SPDX-License-Identifier: MPL-2.0

# Configuration file for golangci-lint
# See https://golangci-lint.run/usage/configuration/ for more information

version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: all

issues:
  max-issues-per-linter: 0
  max-same-issues: 0