# SPDX-FileCopyrightText: 2025 The templig contributors.
# SPDX-License-Identifier: MPL-2.0

env: dev
database:
    url: mydb.instance.db
    user: myDBUser
    pass: {{ read "dbpass" | required "need dbpass file to read db password" | quote }}
listen_port: 1234